apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: devops-app
data:
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  API_BASE_URL: "http://user-service:3001"
  DATABASE_URL: "mongodb://mongodb:27017/devops_app"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: devops-app
data:
  nginx.conf: |
    upstream user-service {
        server user-service:3001;
    }
    
    server {
        listen 80;
        server_name localhost;
        
        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
            try_files $uri $uri/ /index.html;
        }
        
        location /api/ {
            proxy_pass http://user-service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        
        location /health {
            access_log off;
            return 200 "healthy\n";
            add_header Content-Type text/plain;
        }
    }

