apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: devops-project
  namespace: argocd
spec:
  description: "DevOps End-to-End Project"
  
  sourceRepos:
  - 'https://github.com/YOUR-USERNAME/devops-k8s-manifests.git'
  
  destinations:
  - namespace: 'devops-app'
    server: https://kubernetes.default.svc
  - namespace: 'devops-*'
    server: https://kubernetes.default.svc
  
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRole
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRoleBinding
  
  namespaceResourceWhitelist:
  - group: ''
    kind: ConfigMap
  - group: ''
    kind: Secret
  - group: ''
    kind: Service
  - group: 'apps'
    kind: Deployment
  - group: 'apps'
    kind: ReplicaSet
  - group: 'networking.k8s.io'
    kind: Ingress
  - group: 'networking.k8s.io'
    kind: NetworkPolicy
  
  roles:
  - name: admin
    description: "Admin role for devops project"
    policies:
    - p, proj:devops-project:admin, applications, *, devops-project/*, allow
    - p, proj:devops-project:admin, repositories, *, *, allow
    groups:
    - devops-admins
  
  - name: developer
    description: "Developer role for devops project"
    policies:
    - p, proj:devops-project:developer, applications, get, devops-project/*, allow
    - p, proj:devops-project:developer, applications, sync, devops-project/*, allow
    groups:
    - devops-developers

