apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-service
  namespace: argocd
  labels:
    app: user-service
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: devops-project
  
  source:
    repoURL: https://github.com/Mohit7019/devops-k8s-manifests_mohit.git
    targetRevision: HEAD
    path: environments/prod/user-service
  
  destination:
    server: https://kubernetes.default.svc
    namespace: devops-app
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  revisionHistoryLimit: 10
  
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas

